/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package imagetypeconverter;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author semih
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        comboBoxItemsAdd(imageFileType, cmbFileType);
        txtOutFilePath.setText(FileSystemView.getFileSystemView().getHomeDirectory().toString());
    }

    String[] imageFileType = {"jpg", "jpeg", "png", "bmp", "gif", "tiff", "tif"};
    JFileChooser fChooserConvertFilePath = new JFileChooser();
    JFileChooser fChooserSaveFilePath = new JFileChooser();
    FileNameExtensionFilter fType = new FileNameExtensionFilter("Resim Dosyaları (*.jpg, *.jpeg, *.png, *.gif, *.tiff, *.tif)", "jpg", "JPG", "jpeg", "JPEG", "png", "PNG", "gif", "GIF", "tiff", "TIFF", "tif", "TIF");

    private void comboBoxItemsAdd(String[] array, JComboBox cmb) {
        cmb.removeAllItems();

        for (String item : array) {
            cmb.addItem(item);
        }
    }

    private void imageConvert(String oldImagePath, String outPath, String newImageName, int selectedIndex) {
        try {
            BufferedImage bImage = ImageIO.read(new File(oldImagePath));

            if (imageFileType[selectedIndex].equals("jpg") || imageFileType[selectedIndex].equals("jpeg")) {
                bImage = convertToJpg(bImage);
            }

            boolean sucess = ImageIO.write(bImage, imageFileType[selectedIndex], new File(outPath + File.separator + newImageName + "." + imageFileType[selectedIndex]));

            if (sucess) {
                JOptionPane.showMessageDialog(this, "Dosyanız başarıyla ." + imageFileType[selectedIndex] + " şeklinde dönüştürüldü", "Başarılı Dönüşüm", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Bir hata ile karşılaşıldı. Kaydedilemedi\nDosya yolu : " + outPath + File.separator + newImageName + "." + imageFileType[selectedIndex], "Başarısız Dönüşüm", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Bir hata ile karşılaşıldı. \n Error Mesaage : " + e.getMessage(), "Başarısız Dönüşüm", JOptionPane.ERROR_MESSAGE);
        }

    }

    private BufferedImage convertToJpg(BufferedImage image) {
        BufferedImage buff = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_INT_RGB);

        Graphics2D convertBuff = buff.createGraphics();
        convertBuff.setColor(Color.WHITE);
        convertBuff.fillRect(0, 0, image.getWidth(), image.getHeight());
        convertBuff.drawImage(image, 0, 0, null);
        convertBuff.dispose();

        return buff;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbFileType = new javax.swing.JComboBox<>();
        txtNewFileName = new javax.swing.JTextField();
        txtConvertFilePath = new javax.swing.JTextField();
        btnSelectFile = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtOutFilePath = new javax.swing.JTextField();
        btnSelectOutFilePath = new javax.swing.JButton();
        btnConvert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resim Dönüştürücü");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(214, 192, 179));

        jPanel1.setBackground(new java.awt.Color(228, 224, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Dönüştürülecek Dosya :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Yeni Dosya Adı :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Dosya Türü :");

        cmbFileType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbFileType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFileType.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNewFileName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtConvertFilePath.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSelectFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSelectFile.setText("SEÇ");
        btnSelectFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFileActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Kaydedilecek Yer :");

        txtOutFilePath.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSelectOutFilePath.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSelectOutFilePath.setText("SEÇ");
        btnSelectOutFilePath.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSelectOutFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectOutFilePathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFileType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtConvertFilePath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectFile))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtOutFilePath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectOutFilePath))
                    .addComponent(txtNewFileName))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtConvertFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectFile))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtOutFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectOutFilePath))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbFileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConvert.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnConvert.setText("Dönüştür");
        btnConvert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(btnConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConvert)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFileActionPerformed
        // TODO add your handling code here:
        fChooserConvertFilePath.setDialogTitle("Bir Dosya Seçin");
        fChooserConvertFilePath.setFileFilter(fType);
        int result = fChooserConvertFilePath.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            txtConvertFilePath.setText(fChooserConvertFilePath.getSelectedFile().toString());
        }
    }//GEN-LAST:event_btnSelectFileActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
        imageConvert(txtConvertFilePath.getText(), txtOutFilePath.getText(), txtNewFileName.getText(), cmbFileType.getSelectedIndex());
    }//GEN-LAST:event_btnConvertActionPerformed

    private void btnSelectOutFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectOutFilePathActionPerformed
        // TODO add your handling code here:
        fChooserSaveFilePath.setDialogTitle("Kayedilecek Yer");
        fChooserSaveFilePath.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int result = fChooserSaveFilePath.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            txtOutFilePath.setText(fChooserSaveFilePath.getSelectedFile().toString());
        }
    }//GEN-LAST:event_btnSelectOutFilePathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.JButton btnSelectFile;
    private javax.swing.JButton btnSelectOutFilePath;
    private javax.swing.JComboBox<String> cmbFileType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtConvertFilePath;
    private javax.swing.JTextField txtNewFileName;
    private javax.swing.JTextField txtOutFilePath;
    // End of variables declaration//GEN-END:variables
}
